# This is the world defaults configuration file for Paper.
# As you can see, there's a lot to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
#
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or check the docs page.
#
# Configuration options here apply to all worlds, unless you specify overrides inside
# the world-specific config file inside each world folder.
#
# Docs: https://docs.papermc.io/
# Discord: https://discord.gg/papermc
# Website: https://papermc.io/

_version: 28
anticheat:
  anti-xray:
    enabled: false # ANTI_XRAY
fixes:
  disable-unloaded-chunk-enderpearl-exploit: false
hopper:
  disable-move-event: false
lootables:
  auto-replenish: false
